name: Mi primer Github action

on:
  push:
    branches: ["main"]

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
      run: echo "hola, este es mi primer mensaje"
